

@baseUrl = http://localhost:8093
@cardsUrl = {{baseUrl}}/api/v1/cards

# GET health
GET {{baseUrl}}/actuator/health

###

# SHUTDOWN app via actuator
POST {{baseUrl}}/actuator/shutdown

###

# Refresh config using actuator
POST {{baseUrl}}/actuator/refresh

###

# GET build version
GET {{cardsUrl}}/version

###

# GET java version
GET {{cardsUrl}}/java-version

###

# GET env variable
GET {{cardsUrl}}/env-variable/SPRING_PROFILES_ACTIVE

###

# GET contact information
GET {{cardsUrl}}/contact-info

###
# Create a loan
POST {{cardsUrl}}
Content-Type: application/json

{
  "mobileNumber": "+49171123456789"
}

###

# Fetch a loan
GET {{cardsUrl}}/+49171123456789

###

# Update a loan
PUT {{cardsUrl}}
Content-Type: application/json

{
  "mobileNumber": "+49171123456789",
  "cardNumber": "1311227349353163",
  "cardType": "Credit Card",
  "totalLimit": 5000,
  "amountUsed": 5000,
  "availableAmount": 5000
}